 create database shopping_trends;
 show databases;
 use shopping_trends;
 select * from customer limit 5;
 
 -- Q.1. What is the total revenue generated by male vs. female customers?
select 
	gender,
    sum(purchase_amount) as Total_Revenue
from customer
group by 1;


-- Q.2. Caluclate Impact of Discount on Revenue?
SELECT 
	discount_applied,
	SUM(purchase_amount) AS total_revenue,
	round(AVG(purchase_amount),2) AS avg_spend
FROM customer
GROUP BY discount_applied;


-- Q.3. Which customers used a discount but still spent more than the average purchase amount? 
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer
);


-- Q.4. Which are the top 5 products with the highest average review rating?
select 
	item_purchased,
    round(avg(review_rating),2) as Average_Product_Rating
from customer
group by 1
order by 2 desc
limit 5;


-- Q.5. Calculate Revenue Contribution by Subscriber and Non-Subscirber?
SELECT 
	subscription_status,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;


-- Q.6. Compare the average Purchase Amounts between Standard and Express Shipping?
select 
	shipping_type,
	round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;


-- Q.7. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select 
	subscription_status,
    count(customer_id) as total_customer,
    round(avg(purchase_amount),2) as Average_spend,
    round(sum(purchase_amount),2) as Total_Revenue
from customer
group by 1
order by 3,2 desc;


-- Q.8. Which 5 products have the highest percentage of purchases with discounts applied?
select
	item_purchased,
    round(sum(case when discount_applied = 'yes'then 1 else 0 end)/count(*)*100,2) as Discount_rate
from customer
group by 1
order by Discount_rate desc
limit 5;


-- Q.9. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?
with Customer_type as(
	select 
		customer_id,
        previous_purchases,
	case 
		when previous_purchases = 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
        end as customer_segment
	from customer
)
select
	customer_segment,
    count(*) as "Number_of_Customer"
from customer_type
group by customer_segment;


-- Q10. What are the top 3 most purchased products within each category? 
with items_counts as (
	select
		category,
        item_purchased,
        count(customer_id) as total_orders,
        ROW_NUMBER() over(partition by category order by count(customer_id)desc) as item_rank
	from customer
    group by category, item_purchased
)
 select
	item_rank,
    category,
    item_purchased,
    total_orders
from items_counts
where item_rank <= 3;


-- Q.11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
	subscription_status,
    count(customer_id) as Repeat_Buyers
from customer
where previous_purchases > 5
group by 1;


-- Q.12. What is the revenue contribution of each age group? 
select
	age_group,
    sum(purchase_amount) as Total_revenue
from customer
group by 1 
order by Total_revenue desc;